### ISSUE TITLE
Hello,do you continue to do this job ？

### ISSUE THREAD

**Issue by optimal16** [youxiamotors/driveassist-alpha#3]
Hello , your demos are great
 I feel so Exciting  can find your message .,I notice you haven't updated your message for a long time,do you continue to do this work and how things are going？ 
And I notice the picture in https://www.zybuluo.com/greensea/note/124201 can not show  normally.
so can you give me a hand. my QQ num is 921224888 ,and I can not join in the QQ group 302975729
thanks anyway!

**Comment by greensea** [comment]
那篇文章中的图片是放在以前游侠网站的 CDN 上的，我没有备份，现在已经不太可能恢复图片了。
你可以再加一次那个自动驾驶群，可能之前我没看到申请入群的消息。
这个项目目前已经暂停了，应该不会再继续开发了。
